dist: xenial
language: c
sudo: required
os: linux
apt:
    update: true

before_install:
    - sudo ./install-deps

matrix:
    include:
     - os: linux
        env: CC=gcc CXX=g++
        script: ./configure
     - os: linux
         env: CC=clang CXX=clang++
         script: ./configure
     - os: linux
         compiler: gcc
         script: ./configure
     - os: linux
         compiler: clang
         script: ./configure


