dist: xenial
language: c
sudo: required
os: linux
apt:
    update: true

before_install:
    - sudo ./install-deps

matrix:
    include: 
        - env: "gcc 5.4.0"
            compiler:
                - gcc
            script:
                - ./configure
        - env: "clang 5.0.0"
            compiler:
                - clang
            script:
                - ./configure

