dist: xenial
language: c
sudo: required
apt:
    update: true
before_install:
     - sudo ./install-deps
matrix:
    include:
        - os: linux
          compiler: gcc
          env: TEST=gcc
        - os: linux
          compiler: clang
          env: TEST=clang

script:
     - ./configure

